---
apiVersion: v1
kind: Secret
metadata:
  name: fizzy
type: Opaque
data:
  SECRET_KEY_BASE: cGxhY2Vob2xkZXIK
  MAILER_FROM_ADDRESS: cGxhY2Vob2xkZXIK
  SMTP_ADDRESS: cGxhY2Vob2xkZXIK
  SMTP_PORT: cGxhY2Vob2xkZXIK
  SMTP_USERNAME: cGxhY2Vob2xkZXIK
  SMTP_PASSWORD: cGxhY2Vob2xkZXIK

---
apiVersion: v1
kind: Secret
metadata:
  name: fizzy-tls
type: Opaque
data:
  tls.crt: cGxhY2Vob2xkZXIK
  tls.key: cGxhY2Vob2xkZXIK