apiVersion: v1
kind: Service
metadata:
  name: mailpit
spec:
  type: ClusterIP
  ports:
  - port: ClusterIP
    port: 1025
    targetPort: 1025
    protocol: TCP
    name: smtp
  - port: ClusterIP
    port: 8025
    targetPort: 8025
    protocol: TCP
    name: ui
  selector:
    app: mailpit
