---
apiVersion: v1
kind: Secret
metadata:
  name: master-keys
type: Opaque
data:
  rails: cGxhY2Vob2xkZXIK
  lockbox: cGxhY2Vob2xkZXIK
---
apiVersion: v1
kind: Secret
metadata:
  name: fakturo-tls
type: Opaque
data:
  tls.crt: cGxhY2Vob2xkZXIK
  tls.key: cGxhY2Vob2xkZXIK
---
apiVersion: v1
kind: Secret
metadata:
  name: fakturo-rabbitmq
type: Opaque
data:
  connection_string: YW1xcDovL1VTRVJOQU1FOlBBU1NXT1JEQHJhYmJpdG1x