---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
  - path: config/crd/standard
    repoURL: https://github.com/kubernetes-sigs/gateway-api.git
    targetRevision: v1.4.0
  project: infra

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  sources:
  - path: docs/content/reference/dynamic-configuration
    repoURL: https://github.com/traefik/traefik.git
    targetRevision: v3.6.6
    directory:
      include: kubernetes-gateway-rbac.yml
  - path: ''
    repoURL: https://traefik.github.io/charts
    targetRevision: 38.0.1
    chart: traefik
    helm:
      values: |
        providers:
          kubernetesGateway:
            enabled: true
  project: infra
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
